### ISSUE TITLE
ASCI

### ISSUE THREAD

**Issue by bognabognabogna** [linsalrob/PhiSpy#19]
Hello,

Thank you for sharing your amazing software.
I would be very grateful if anyone could help me on the following issue:

SyntaxError: Non-ASCII character '\xc5' in file /Users/bognasmug/Applications/PhiSpy/modules/helper_functions.py on line 35, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I get that error when I run:
./PhiSpy.py -i [organism_directory] -o [output_dir] -c

**Comment by pdec** [comment]
Hello,

I suspect, there were ASCII characters either in your [organism_directory] or [output_directory]. It would be helpful if you could share the whole command you used to run PhiSpy.

It also seems like you were using old version of PhiSpy.
Please try out the newest one - [release v3.4](https://github.com/linsalrob/PhiSpy/releases/tag/v3.4) and let us know whether the error still occurs or not.

**Comment by linsalrob** [comment]
This has been resolved. `helper_functions.py` contains an appropriate encoding definition:

```
# -*- coding: utf-8 -*-
```
