### ISSUE TITLE
Lower the gene window

### ISSUE THREAD

**Issue by deprekate** [linsalrob/PhiSpy#20]
([helper_functions.py](https://github.com/linsalrob/PhiSpy/blob/7de1d69fbe61224d2c7c29866ea3a3b29c7ee948/modules/helper_functions.py#L49))

The current number is 30, which seems a little high, as when I run it on ecoli k12 I do not get any prophages found. 

This might be a bug, it looks like the -n and -w flags got mixed up.  
[This](https://github.com/linsalrob/PhiSpy/blob/7de1d69fbe61224d2c7c29866ea3a3b29c7ee948/modules/evaluation.py#L317) line looks like it should be self.number as noted [here](https://github.com/linsalrob/PhiSpy/blob/7de1d69fbe61224d2c7c29866ea3a3b29c7ee948/modules/helper_functions.py#L47)

**Comment by linsalrob** [comment]
This has been fixed in version 3.5
