### ISSUE TITLE
Move all command line argument parsing code in PhiSpy.py to the helper_functions.py file

### ISSUE THREAD

**Issue by deprekate** [linsalrob/PhiSpy#24]
Everything is broken for me.  I just cloned the master branch to check out the Ochro stuff, and the misc training data code from the latest push is breaking things

**Comment by pdec** [comment]
That's weird as I used that version to run the Ochro stuff
could you provide more details?

**Comment by linsalrob** [comment]
Phispy is working for me. Is it still broken?

Rob
