### ISSUE TITLE
Selecting features measurements

### ISSUE THREAD

**Issue by pdec** [linsalrob/PhiSpy#36]
The idea is to be able to select which measurements are selected for classification with Random Forest. This would allow investigating the influence of each metric for prophage discovery. 

Maybe this could be available in Jupyter Notebook?

**Comment by linsalrob** [comment]
Take a look at the [interactive PhiSpy jupyter notebook](https://github.com/linsalrob/PhiSpy/tree/master/jupyter_notebooks) that shows how to see all the features used for the RFs and how to identify prophages.
