### ISSUE TITLE
Not phage function

### ISSUE THREAD

**Issue by pdec** [linsalrob/PhiSpy#49]
Shouldn't there be an `if` rather than `elif` in L126? 
https://github.com/linsalrob/PhiSpy/blob/8c09a44d58892be74ad87ff638d1a46bb7ac8c4f/PhiSpyModules/classification.py#L122-L127
It seems like it should be checked separately
Eg., It won't work for "phage shock protein" as it first gets classified as phage function due to "phage" word.

**Comment by linsalrob** [comment]
Yes, I think this is correct.
