### ISSUE TITLE
Parameter to indicate file name prefixes+

### ISSUE THREAD

**Issue by ireneortega** [linsalrob/PhiSpy#58]
What is the parameter required to indicate file name prefixes?

I am interested in this part of the information:

**file name prefixes**
By default the outputs from PhiSpy.py have standard names. If you supply a file name prefix it will be prepended to all the file so that you can run PhiSpy.py on multiple genomes and have the outputs in the same directory without overwriting each other.

I can't find anything related when typing `-h`

**Comment by linsalrob** [comment]
The correct parameter is 

```
  -p FILE_PREFIX, --file_prefix FILE_PREFIX
                        An optional prefix to prepend to all of the output
                        files
```
