### ISSUE TITLE
pVOG db no longer available

### ISSUE THREAD

**Issue by raw-lab** [linsalrob/PhiSpy#61]
I found this link. 
https://zenodo.org/record/4576599#.ZB3UHo7MI5k

Maybe putting it on osf?

many thanks,
Rick

**Comment by linsalrob** [comment]
That database is not supported, and I would encourage you not to use that old version. Instead, you should consider updating to one of the newer databases. We currently use [PHROGS](https://phrogs.lmge.uca.fr/) and they promise a new version later in 2023.
