### ISSUE TITLE
conda installation failed

### ISSUE THREAD

**Issue by dr-joe-wirth** [linsalrob/PhiSpy#62]
I installed using `conda install -c bioconda psispy`. But running `phispy` produced the following error:
```
Traceback (most recent call last):                                                                                                                                         
  File "/scicomp/home-pure/uma2/miniconda3/envs/phispy/bin/phispy", line 7, in <module>                                                                                    
    from PhiSpy.py import main                                                                                                                                             
ModuleNotFoundError: No module named 'PhiSpy.py'; 'PhiSpy' is not a package
```

I fixed the error by modifying the `phispy` file:
  * I imported `os`
  * I added the directory containg `PhiSpy.py` to the path using `sys` and `os`: `sys.path.insert(0,os.path.join(sys.path[0], '<path>/miniconda3/envs/phispy/bin'))`
  * I changed the import statement from `from PhiSpy.py import main` to `from PhiSpy import main`
  * Finally, `sys.argv` was not being passed to `main` at the end of the file. So I modified the line from `sys.exit(main())` to `sys.exit(main(sys.argv))`

These changes allowed the command `phispy` to work

**Comment by linsalrob** [comment]
This should not be necessary, and I don't know why you had to do this. [ All conda tests currently pass](https://anaconda.org/bioconda/phispy).

Please don't do this, as you will almost certainly break things.

**Comment by linsalrob** [comment]
I think the issue is the command. Try `PhiSpy.py` instead of `phispy`.
