### ISSUE TITLE
 PhiSpy does not support Python 3

### ISSUE THREAD

**Issue by chris-rands** [linsalrob/PhiSpy#7]
PhiSpy appears to support Python 2 only. This could be documented in the README files.

Ideally Python 3 support would also be added since Python 2 will be not be maintained in 2020.

**Comment by JFsanchezherrero** [comment]
Hi there, 
I was wondering if the developers @linsalrob, @scottdaniel, @deprekate are planning to move to python3 in the following future?

Also I wonder if they could fix and update git with the bug fix mentioned (a year ago) in issue #5 which it is already solved by another user (@signetang) https://github.com/linsalrob/PhiSpy/issues/6#issuecomment-428915490

It would make things much easier.

On the other, if they do not support python3 and neither fix bugs, I wonder if it would be possible to include and modify the code within my own pipeline and cite accordingly.

Thank you very much

**Comment by linsalrob** [comment]
With the latest releases PhiSpy now fully supports Python 3.
